version: "3.9"

services:
    db:
        container_name: db
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data

    next-app:
        depends_on:
            - db
        container_name: next-app
        env_file:
            - .env
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                POSTGRES_PRISMA_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB}:5432/postgres
                POSTGRES_URL_NON_POOLING: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_DB}:5432/postgres
                GITHUB_ID: ${GITHUB_ID}
                GITHUB_SECRET: ${GITHUB_SECRET}
                AZURE_AD_CLIENT_ID: ${AZURE_AD_CLIENT_ID}
                AZURE_AD_CLIENT_SECRET: ${AZURE_AD_CLIENT_SECRET}
                AZURE_AD_TENANT_ID: ${AZURE_AD_TENANT_ID}

        restart: always
    proxy:
        volumes:
            - ./proxy/cert/:/etc/letsencrypt
        build:
            context: ./proxy
        restart: always
        container_name: proxy
        ports:
            - 80:80
            - 443:443
        env_file:
            - .env
        depends_on:
            - db
            - next-app

volumes:
    pgdata: {}
